server:
  port: ${PORT:8761}
spring:
  application:
    name:
      eureka-server

  profiles:
    active: ${PROFILE:dev}

  config:
    active:
      on-profile: dev
    import: optional:configserver:http://localhost:9991

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    server:
      enable-self-preservation: false