server:
  port: ${PORT:9991}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
#         uri: ${CONFIG_URL:http://github.com/leomag/config-server.git}
          uri: file:///Users//leomag//Desktop//samokat-server//configs-repo
          username: ${REPO_USER:leo}
          password: ${REPO_PASSWORD:leo}
          default-label: main
          search-paths: "{application}"