version: '3.9'

services:

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: "samokat-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database:/docker-entrypoint-initdb.d.ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 10s
      timeout: 5s

  adminer:
    image: adminer

    ports:
      - "8082:8080"
    depends_on:
      - db
